### ISSUE TITLE
ObjectTK 2.0 Checklist

### ISSUE THREAD

**Issue by varon** [opentk/ObjectTK#14]
Current tasks:

- [ ] Add .obj importer
- [ ] Add some basic primitive vertex arrays
- [ ] Add typed Shaders
- [ ] Add 3D package

**Comment by uzername** [comment]
Also, more examples, please. For example, a sphere, controlled by WASD, moving around the scene of cubes
